In [1]:
import numpy as np
np.__version__

'1.18.5'

For help and documentation
np.<"Tab">
or np?

## Exploring Data Types

### Basic Data Types

In [6]:
x = 2
y = 2.1
z = "two"
p = True
q = None
r = np.nan

print("Data type of x is", type(x))
print("Data type of y is", type(y))
print("Data type of z is", type(z))
print("Data type of p is", type(p))
print("Data type of q is", type(q))
print("Data type of r is", type(r))

Data type of x is <class 'int'>
Data type of y is <class 'float'>
Data type of z is <class 'str'>
Data type of p is <class 'bool'>
Data type of q is <class 'NoneType'>
Data type of r is <class 'float'>


### List

In [11]:
L = list(range(5))
print(L)
print(type(L))
print([type(each) for each in L])

[0, 1, 2, 3, 4]
<class 'list'>
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


In [13]:
L2 = [str(each) for each in L]
print(L2)
print(type(L2))
print([type(each) for each in L2])

['0', '1', '2', '3', '4']
<class 'list'>
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [14]:
L3 = [x, y, z, p, q, r]
print(L3)
print(type(L3))
print([type(each) for each in L3])

[2, 2.1, 'two', True, None, nan]
<class 'list'>
[<class 'int'>, <class 'float'>, <class 'str'>, <class 'bool'>, <class 'NoneType'>, <class 'float'>]


### Fixed type Arrays in python
#### !not numpy arrays

In [15]:
import array
A = array.array('i', L) #here i indicates that each entry is an integer
A

array('i', [0, 1, 2, 3, 4])

### Numpy Arrays

In [16]:
np.array([1, 2, 4, 3, 5])

array([1, 2, 4, 3, 5])

In [17]:
np.array([3.14, 2, 4, 3])

array([3.14, 2.  , 4.  , 3.  ])

In [18]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [21]:
#create an array of zeroes

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
#create an array of zeroes of data type as integers

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#create a 3x5 array of one's

np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#create a 3x4 array filled with 3.14

np.full([3, 4], 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [28]:
#create an array filled with linear sequence

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
#create an array of equally spaced numbers

np.linspace(0, 15, 6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [33]:
#create an 3x3 array of uniformly distributed
#random numbers between 0 and 1

np.random.random((3,3))

array([[0.84913124, 0.28502097, 0.94546931],
       [0.5989981 , 0.43918127, 0.77450468],
       [0.56013366, 0.47261245, 0.45014158]])

In [37]:
#create an 3x3 array of normally distributed
#random numbers with mu = 0, stdev = 1

np.random.normal(0, 1, (3,3))

array([[-1.30776182, -0.09535716,  1.71593346],
       [ 1.2707295 , -0.99131439,  0.52520429],
       [-0.53070082,  0.66874778,  0.55462402]])

In [38]:
#create an 3x3 array of random integers between 0 to 10

np.random.randint(0, 10, (3,3))

array([[2, 2, 1],
       [7, 5, 0],
       [8, 9, 6]])

In [40]:
#create a 4x4 identity matrix

np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [42]:
#set seed for reproducibility

np.random.seed(42)